import { NextResponse } from "next/server";
import { getAccessToken } from "@/lib/get-access-token";
import { bulkCreateSales, clearSales, initSpreadsheet } from "@/lib/google-sheets";
import type { Sale } from "@/types";

const SEED_SALES: Omit<Sale, "id" | "createdAt">[] = [
  // Abril 2025
  { saleDate: "2025-04-10", product: "Paquete", status: "Emitida", paymentStatus: "GP", amount: 4244221.35, commission: 812000, currency: "CLP", clientName: "Cox Bustaman.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-04-10", product: "Paquete", status: "Emitida", paymentStatus: "GP", amount: 4244221.35, commission: 812000, currency: "CLP", clientName: "Bonati Corder.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-04-10", product: "Paquete", status: "Emitida", paymentStatus: "GP", amount: 4244221.35, commission: 812000, currency: "CLP", clientName: "María Florenci.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-04-10", product: "Hotel", status: "Emitida", paymentStatus: "GP", amount: 1690356.63, commission: 320000, currency: "CLP", clientName: "María Cecilia L.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-04-10", product: "Hotel", status: "Emitida", paymentStatus: "GP", amount: 2530757.94, commission: 578000, currency: "CLP", clientName: "Francisca Car.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-04-11", product: "Traslado", status: "Emitida", paymentStatus: "TC", amount: 27473.41, commission: 3297, currency: "CLP", clientName: "Bonati Corder.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-04-11", product: "Traslado", status: "Emitida", paymentStatus: "TC", amount: 46886.27, commission: 5626, currency: "CLP", clientName: "Gastellu Ferre.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-04-14", product: "Traslado", status: "Emitida", paymentStatus: "TC", amount: 50612.56, commission: 6074, currency: "CLP", clientName: "Bonati Corder.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  // Mayo 2025
  { saleDate: "2025-05-05", product: "Paquete", status: "Emitida", paymentStatus: "GP", amount: 4149413.12, commission: 459000, currency: "CLP", clientName: "Amenábar Al.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-05-13", product: "Hotel", status: "Emitida", paymentStatus: "TD", amount: 597084.01, commission: 109000, currency: "CLP", clientName: "María José Le.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-05-16", product: "Paquete", status: "Emitida", paymentStatus: "TC", amount: 4274155.81, commission: 685000, currency: "CLP", clientName: "MACARENA D.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  // Junio 2025
  { saleDate: "2025-06-06", product: "Paquete", status: "Emitida", paymentStatus: "TC", amount: 2385064.01, commission: 173372, currency: "CLP", clientName: "Guerrero Flore.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  // Julio 2025
  { saleDate: "2025-07-23", product: "Paquete", status: "Emitida", paymentStatus: "PR+TC", amount: 999363.61, commission: 235000, currency: "CLP", clientName: "Rodriguez, Gui.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  // Agosto 2025
  { saleDate: "2025-08-11", product: "Parque temático", status: "Emitida", paymentStatus: "PR+TC", amount: 2531706.60, commission: 50000, currency: "CLP", clientName: "Donoso Torres.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-08-18", product: "Parque temático", status: "Emitida", paymentStatus: "PR+TC", amount: 2526208.78, commission: 50000, currency: "CLP", clientName: "FELIÚ SLATER.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  // Septiembre 2025
  { saleDate: "2025-09-15", product: "Traslado", status: "Emitida", paymentStatus: "PR+TC", amount: 44895.66, commission: 5387, currency: "CLP", clientName: "Lecaros Lanas.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-09-24", product: "Actividad", status: "Emitida", paymentStatus: "PR+TC", amount: 129075.01, commission: 38723, currency: "CLP", clientName: "Rodiek Gonzál.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-09-24", product: "Vuelo", status: "Emitida", paymentStatus: "PR+TC", amount: 767622.00, commission: 7629, currency: "CLP", clientName: "Rodiek Gonzál.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-09-24", product: "Vuelo", status: "Emitida", paymentStatus: "PR+TC", amount: 978472.00, commission: 9355, currency: "CLP", clientName: "Rodiek Gonzál.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-09-24", product: "Paquete", status: "Emitida", paymentStatus: "PR+TC", amount: 2799402.93, commission: 273000, currency: "CLP", clientName: "Herrera Pánic.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-09-29", product: "Vuelo", status: "Emitida", paymentStatus: "PR+TC", amount: 546137.00, commission: 10840, currency: "CLP", clientName: "Curtis Hernan.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-09-29", product: "Vuelo", status: "Emitida", paymentStatus: "TD", amount: 684085.00, commission: 11578, currency: "CLP", clientName: "Curtis Hernan.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-09-30", product: "Paquete", status: "Emitida", paymentStatus: "PR+TC", amount: 998007.42, commission: 141000, currency: "CLP", clientName: "Jaschan Little.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-09-30", product: "Paquete", status: "Emitida", paymentStatus: "PR+TC", amount: 1079360.09, commission: 143000, currency: "CLP", clientName: "Jaschan Little.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  // Octubre 2025
  { saleDate: "2025-10-08", product: "Paquete", status: "Emitida", paymentStatus: "PR+TC", amount: 679412.37, commission: 50000, currency: "CLP", clientName: "José Alexis Cif.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-10-28", product: "Paquete", status: "Emitida", paymentStatus: "PR+TC", amount: 779858.41, commission: 76500, currency: "CLP", clientName: "Alejandro And.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-10-31", product: "Traslado", status: "Emitida", paymentStatus: "PR+TC", amount: 59490.81, commission: 3569, currency: "CLP", clientName: "Troncoso Cast.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-10-31", product: "Traslado", status: "Emitida", paymentStatus: "PR+TC", amount: 37503.15, commission: 4500, currency: "CLP", clientName: "Troncoso Cast.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  // Noviembre 2025
  { saleDate: "2025-11-02", product: "Paquete", status: "Emitida", paymentStatus: "PR+TC", amount: 4075960.72, commission: 280000, currency: "CLP", clientName: "Ahumada Moli.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-11-05", product: "Actividad", status: "Emitida", paymentStatus: "PR+TC", amount: 54270.94, commission: 16281, currency: "CLP", clientName: "Herrera Pánic.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-11-11", product: "Hotel", status: "Emitida", paymentStatus: "TC", amount: 4201503.69, commission: 900000, currency: "CLP", clientName: "Drina Eugenia.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-11-12", product: "Vuelo", status: "Emitida", paymentStatus: "GP", amount: 4365932.00, commission: 77191, currency: "CLP", clientName: "Migone Rettig.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-11-28", product: "Traslado", status: "Emitida", paymentStatus: "PR+TC", amount: 628352.50, commission: 200000, currency: "CLP", clientName: "Migone Rettig.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  // Diciembre 2025
  { saleDate: "2025-12-16", product: "Vuelo", status: "Emitida", paymentStatus: "PR+TC", amount: 8053544.00, commission: 121725, currency: "CLP", clientName: "Fernández Ch.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-12-27", product: "Vuelo", status: "Emitida", paymentStatus: "TC", amount: 1086744.00, commission: 20154, currency: "CLP", clientName: "Romo Pino, Fa.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-12-27", product: "Vuelo", status: "Emitida", paymentStatus: "TC", amount: 148986.54, commission: 40000, currency: "CLP", clientName: "Romo Pino, Fa.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-12-27", product: "Vuelo", status: "Emitida", paymentStatus: "TC", amount: 391555.20, commission: 45000, currency: "CLP", clientName: "Romo Pino, Fa.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2025-12-27", product: "Paquete", status: "Emitida", paymentStatus: "TC", amount: 3976654.53, commission: 320918, currency: "CLP", clientName: "Pesce Romo, I.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  // Enero 2026
  { saleDate: "2026-01-14", product: "Hotel", status: "Emitida", paymentStatus: "TC", amount: 672462.50, commission: 94145, currency: "CLP", clientName: "Patricia Ugart.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-01-14", product: "Hotel", status: "Emitida", paymentStatus: "TC", amount: 1324927.32, commission: 325000, currency: "CLP", clientName: "Patricia Ugart.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-01-28", product: "Hotel", status: "Emitida", paymentStatus: "TD", amount: 110369.29, commission: 0, currency: "CLP", clientName: "Diego Alejandr.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-01-28", product: "Hotel", status: "Emitida", paymentStatus: "TD", amount: 69429.56, commission: 0, currency: "CLP", clientName: "Diego Alejandr.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  // Febrero 2026
  { saleDate: "2026-02-02", product: "Hotel", status: "Emitida", paymentStatus: "TD", amount: 87843.72, commission: 0, currency: "CLP", clientName: "Sofía Antonia.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-02-02", product: "Hotel", status: "Emitida", paymentStatus: "TD", amount: 134010.10, commission: 0, currency: "CLP", clientName: "Sofía Antonia.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-02-14", product: "Vuelo", status: "Emitida", paymentStatus: "TC", amount: 1385231.00, commission: 20569, currency: "CLP", clientName: "CONTRERAS G.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-02-14", product: "Vuelo", status: "Emitida", paymentStatus: "TC", amount: 1294904.00, commission: 24630, currency: "CLP", clientName: "CONTRERAS G.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-02-16", product: "Vuelo", status: "Emitida", paymentStatus: "PR+TC", amount: 493419.42, commission: 32000, currency: "CLP", clientName: "RODRIGUEZ RI.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-02-17", product: "Vuelo", status: "Emitida", paymentStatus: "PR+TC", amount: 612770.74, commission: 29000, currency: "CLP", clientName: "FERNANDEZ.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-02-18", product: "Paquete", status: "Emitida", paymentStatus: "TC", amount: 1143277.25, commission: 159000, currency: "CLP", clientName: "CONTRERAS G.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-02-18", product: "Paquete", status: "Emitida", paymentStatus: "TC", amount: 1874418.25, commission: 720000, currency: "CLP", clientName: "JUAN JOSE C.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-02-19", product: "Paquete", status: "Emitida", paymentStatus: "PR+TC", amount: 1295736.53, commission: 80368, currency: "CLP", clientName: "Juarez Medin.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-02-20", product: "Paquete", status: "Emitida", paymentStatus: "TC", amount: 671913.60, commission: 150000, currency: "CLP", clientName: "JUAN JOSE C.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-02-28", product: "Traslado", status: "Emitida", paymentStatus: "TC", amount: 180859.76, commission: 32555, currency: "CLP", clientName: "Juan Jose Co.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-02-28", product: "Traslado", status: "Emitida", paymentStatus: "PR+TC", amount: 284616.26, commission: 42000, currency: "CLP", clientName: "Ugarte Hamilt.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  // Marzo 2026
  { saleDate: "2026-03-04", product: "Paquete", status: "Emitida", paymentStatus: "PR+TC", amount: 1343517.38, commission: 129000, currency: "CLP", clientName: "Rodríguez Gar.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-03-06", product: "Vuelo", status: "Emitida", paymentStatus: "TD", amount: 337782.83, commission: 42000, currency: "CLP", clientName: "Martínez More.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-03-12", product: "Vuelo", status: "Emitida", paymentStatus: "PR+TC", amount: 2025833.00, commission: 0, currency: "CLP", clientName: "Bertin Rodrigu.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-03-26", product: "Paquete", status: "Emitida", paymentStatus: "PR+TC", amount: 693609.13, commission: 85000, currency: "CLP", clientName: "Madeleine Alar.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-03-29", product: "Vuelo", status: "Emitida", paymentStatus: "PR+TC", amount: 1335426.00, commission: 46469, currency: "CLP", clientName: "Bertin Rodrigu.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  // Abril 2026
  { saleDate: "2026-04-01", product: "Actividad", status: "Emitida", paymentStatus: "TD", amount: 16576.28, commission: 0, currency: "CLP", clientName: "Montero arias.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-04-17", product: "Vuelo", status: "Emitida", paymentStatus: "TD", amount: 139822.00, commission: 0, currency: "CLP", clientName: "Matthews Cof.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-04-21", product: "Vuelo", status: "Emitida", paymentStatus: "GP", amount: 1118886.40, commission: 159000, currency: "CLP", clientName: "FLORES SAAV.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-04-21", product: "Vuelo", status: "Emitida", paymentStatus: "GP", amount: 2745125.26, commission: 400000, currency: "CLP", clientName: "JEREZ GUERR.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-04-29", product: "Traslado", status: "Emitida", paymentStatus: "TD", amount: 132190.24, commission: 0, currency: "CLP", clientName: "ARANEDA RIQ.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  // Mayo 2026
  { saleDate: "2026-05-01", product: "Vuelo", status: "Emitida", paymentStatus: "PR+TC", amount: 2260057.06, commission: 544000, currency: "CLP", clientName: "SOCIAS VERA.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-05-04", product: "Actividad", status: "Emitida", paymentStatus: "TD", amount: 18502.79, commission: 0, currency: "CLP", clientName: "SOCIAS VERA.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-05-04", product: "Paquete", status: "Emitida", paymentStatus: "TC", amount: 797170.62, commission: 130000, currency: "CLP", clientName: "Fernandez, Ma.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-05-06", product: "Paquete", status: "Emitida", paymentStatus: "PR+TC", amount: 798539.40, commission: 62000, currency: "CLP", clientName: "ASCENCIO AR.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-05-07", product: "Vuelo", status: "Emitida", paymentStatus: "PR+TC", amount: 1372847.02, commission: 55000, currency: "CLP", clientName: "DEVIA MENES.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
  { saleDate: "2026-05-08", product: "Paquete", status: "Emitida", paymentStatus: "PR+TC", amount: 370266.62, commission: 50000, currency: "CLP", clientName: "Juan Carlos D.", travelDate: "", detail: "", checkIn: "", checkOut: "", clientEmail: "", clientPhone: "", partner: "", notes: "" },
];

export async function POST() {
  try {
    const token = await getAccessToken();
    if (!token) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    await initSpreadsheet(token);
    await clearSales(token);
    const count = await bulkCreateSales(token, SEED_SALES);
    return NextResponse.json({ count });
  } catch (e) {
    console.error("[POST /api/sales/seed]", e);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
